%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/mynteye/imu/data_raw"
image0_topic: "/mynteye/left/image_raw"
image1_topic: "/mynteye/right/image_raw"
output_path: "/home/shane/output-result/vins-fusion/"

cam0_calib: "mynteye_left_pinhole.yaml"
cam1_calib: "mynteye_right_pinhole.yaml"
image_width: 752
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.00504525, -0.99953451, -0.03008828, -0.0003333,
          0.99940984, 0.00401769, 0.03411496, 0.00022486,
          -0.03397819, -0.03024264, 0.9989649, 0.00029498,
          0, 0, 0, 1]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.00167982, -0.99961517, -0.02768934, 0.00000634,
          0.99993863, 0.00137587, 0.01099247, 0.120796,
          -0.01095014, -0.0277061, 0.99955613, 0.00192222,
          0, 0, 0, 1]

# body_T_cam0: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [0.00504525, 0.99940984, -0.03397819, -0.00021302,
#           -0.99953451, 0.00401769, -0.03024264, -0.00032513,
#           -0.03008828, 0.03411496, 0.9989649, -0.00031238,
#           0, 0, 0, 1]

# body_T_cam1: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [0.00167982, 0.99993863, -0.01095014, -0.12076755,
#           -0.99961517, 0.00137587, -0.0277061, -0.00010661,
#           -0.02768934, 0.01099247, 0.99955613, -0.00324904,
#           0, 0, 0, 1]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # (not work)frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.0104          # accelerometer measurement noise standard deviation. 
gyr_n: 0.0001         # gyroscope measurement noise standard deviation.     
acc_w: 0.0015        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
g_norm: 9.8     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
loop_closure: 0                 # start loop closure
fast_relocalization: 0          # useful in real-time and large project
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/shane/output-result/vins-fusion/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
